### ISSUE TITLE
Labelling of RG Template variant

### ISSUE THREAD

**Issue by JanBeutler** [CardiffSchoolOfEngineering/engin-template#8]
Have installed vanilla J2.5 here (http://j25-rg.engineering.cf.ac.uk/) - you have an account here (username: blueflame):
- switched the template to RG website (in template settings)
- inserted a logo - this renders ok in both FF12 and IE7
1. Cannot find where to change the writing "Cardiff School of Engineering" in the banner. Looked also in your hand-over notes, this is not explained in there
2. it renders this text differently in IE7 (has become a two-liner and has shifted upwards, starting next to "School Research")

**Comment by JanBeutler** [comment]
Any progress? I would like to wrap-up these fixes so that we can (1) setup more websites here in ENGIN (2) progress with more dev projects.

**Comment by leetempest** [comment]
This is hard coded into the template. I will need to add a parameter to the template settings and modify the template to pull a different title into the template
